import bcrypt from 'bcryptjs';
const data = {
  users: [
    {
      name: 'Ojay',
      email: 'admin@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: true,
    },
    {
      name: 'Jisco',
      email: 'user@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: 'Free Shirt',
      slug: 'free-shirt',
      category: 'Shirts',
      image: '/images/shirt1.jpg',
      price: 70,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular shirt',
    },
    {
      name: 'Fit Shirt',
      slug: 'fit-shirt',
      category: 'Shirts',
      image: '/images/shirt2.jpg',
      price: 80,
      brand: 'Adidas',
      rating: 4.2,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular shirt',
    },
    {
      name: 'Slim Shirt',
      slug: 'slim-shirt',
      category: 'Shirts',
      image: '/images/shirt3.jpg',
      price: 90,
      brand: 'Raymond',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular shirt',
    },
    {
      name: 'Golf Pants',
      slug: 'golf-pants',
      category: 'Pants',
      image: '/images/pants1.jpg',
      price: 90,
      brand: 'Oliver',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'Smart looking pants',
    },
    {
      name: 'Fit Pants',
      slug: 'fit-pants',
      category: 'Pants',
      image: '/images/pants2.jpg',
      price: 95,
      brand: 'Zara',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular pants',
    },
    {
      name: 'Classic Pants',
      slug: 'classic-pants',
      category: 'Pants',
      image: '/images/pants3.jpg',
      price: 75,
      brand: 'Casely',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular pants',
    },
    {
      name: 'Classic Sneakers',
      slug: 'classic-sneakers',
      category: 'Sneakers',
      image: '/images/3.jpg',
      price: 30,
      brand: 'Casely',
      rating: 3.9,
      numReviews: 1,
      countInStock: 15,
      description: 'A popular sneaker',
    },
    {
      name: 'Classic Bag',
      slug: 'classic-bag',
      category: 'Bags',
      image: '/images/4.jpg',
      price: 35,
      brand: 'Casely',
      rating: 3.5,
      numReviews: 100,
      countInStock: 50,
      description: 'A popular bag',
    },
    {
      name: 'Classic Belt',
      slug: 'classic-belt',
      category: 'Belts',
      image: '/images/5.jpg',
      price: 10,
      brand: 'Casely',
      rating: 5,
      numReviews: 5,
      countInStock: 14,
      description: 'A popular belt',
    },
  ],
};
export default data;